### PR TITLE
fix answer filter regression

### PR DESCRIPTION
**Pull request by pcvera**
Add `.Answer` to the search field, understanding that `.answer` was removed during multi-answer support. (please confirm @rgossiaux @asdfryan)

### CODE REVIEW

**Comment by pcvera** [comment]
it looks like it might just be generated off of the accessor and added to the values on the `.Answer` key because that's the name of the column

From table columns:
```
  {
    Header: "Answer",
    accessor: (row) => row.guesses.map(({ text }) => text).join(" "),
    Cell: AnswerCell,
  },
```

I'm not sure how I feel about relying on that behavior.

**Comment by rgossiaux** [comment]
I think you can add an id of `answer` as one of the options for a column and that will be the accessor name, haven't confirmed though

**Comment by pcvera** [comment]
> I think you can add an id of `answer` as one of the options for a column and that will be the accessor name, haven't confirmed though

Yes! This is a much nicer solution.

**Review by rgossiaux — APPROVED** [review]
lol perfect, thanks!

**Review by asdfryan — APPROVED** [review]
Thanks!

**Pull request merged**
