### PR TITLE
Support blank puzzle urls

### PR DESCRIPTION
**Pull request by asdfryan**
Fixes https://github.com/cardinalitypuzzles/smallboard/issues/67

Tested locally

### CODE REVIEW

**Comment by erwa** [comment]
The "add new puzzle" modal now supports blank URLs, but the "edit puzzle" modal still doesn't.
edit-puzzle-modal

I think there's probably one more place you need to update validation.

**Comment by erwa** [comment]
Also, it would be nice not to show the puzzle name text as a clickable hyperlink if there is no URL. Currently, it still shows up as a link:
empty

I think `title.html` needs to be updated to not include the `<a href=...>` if `puzzle.url` is blank.

**Comment by asdfryan** [comment]
Thanks Anthony for noticing those bugs -- I'll fix them.

**Comment by asdfryan** [comment]
Regarding the href -- right now the link simply redirects to the current page view -- I think that is a reasonable default behavior.

**Comment by erwa** [comment]
Redirecting to the current page is fine, but I think not showing a link at all is clearer.

**Pull request merged**
